Repository AY2324S2-CS2103T-F13-2/tp, pull requests merged in 2024-03, with the labels that each got.

#12 Update AboutUs page with roles, links, and my own photo
  docs/AboutUs.md
  docs/images/ziyang27.png
  docs/team/simhankiong.md
  docs/team/tanyunchao.md
  docs/team/tanziyang.md
  docs/team/tiongchuanyao.md
Labels: documentation

#15 Update readme page
  README.md
Labels: documentation

#16 Add the select feature description in the user guide
  docs/UserGuide.md
Labels: documentation

#21 Update developer guide based on our product
  docs/DeveloperGuide.md
Labels: documentation

#33 Update team member image in AboutUs.md
  docs/AboutUs.md
  docs/images/tanyunchao.png
Labels: documentation

#35 Add upcoming command to UserGuide.md
  docs/UserGuide.md
Labels: documentation

#34 Update UI image
  docs/images/Ui.png
Labels: documentation

#37 Update documentations
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/index.md
Labels: documentation

#47 Change Ui image
  docs/images/Ui.png
Labels: documentation

#50 Add select command
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SelectCommandParser.java
  src/main/java/seedu/address/model/person/IsSamePersonPredicate.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SelectCommandParserTest.java
  src/test/java/seedu/address/model/person/IsSamePersonPredicateTest.java
Labels: enhancement, priority.High, type.Enhancement

#55 Add find by one tag feature
  src/main/java/seedu/address/logic/commands/FindTagsOrCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTagsOrCommandParser.java
  src/main/java/seedu/address/model/tag/TagFoundPredicate.java
  src/main/java/seedu/address/model/tag/TagsOrFoundPredicate.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTagsOrCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindTagsOrCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/tag/TagsOrFoundPredicateTest.java
  src/test/java/seedu/address/testutil/TagBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement

#54 Add last contacted command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LastContactCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/LastContactCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/LastContact.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/LastContactCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/LastContactCommandParserTest.java
  src/test/java/seedu/address/model/person/LastContactTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/SampleDataUtilTest.java
Labels: enhancement

#60 Add find by all tags feature
  src/main/java/seedu/address/logic/commands/FindTagsAndCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTagsAndCommandParser.java
  src/main/java/seedu/address/model/tag/TagsAndFoundPredicate.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/FindTagsAndCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindTagsAndCommandParserTest.java
  src/test/java/seedu/address/model/tag/TagsAndFoundPredicateTest.java
  src/test/java/seedu/address/model/tag/TagsOrFoundPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement

#59 Add identifier to differentiate the two dates in PersonCard
  src/main/java/seedu/address/ui/PersonCard.java
Labels: enhancement, priority.Medium, type.Enhancement

#61 Update edit command to edit lastcontact field
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/LastContact.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/LastContactTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: enhancement

#66 Update UML diagrams for predicate
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PredicateClasses.puml
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: documentation

#77 Change command words to be case-insensitive
  src/main/java/seedu/address/logic/commands/FindTagsAndCommand.java
  src/main/java/seedu/address/logic/commands/FindTagsOrCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.Medium, type.Enhancement

#78 Branch case insensitive tags
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/FindTagsAndCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTagsOrCommandTest.java
  src/test/java/seedu/address/model/tag/TagsAndFoundPredicateTest.java
  src/test/java/seedu/address/model/tag/TagsOrFoundPredicateTest.java
  src/test/java/seedu/address/testutil/TagBuilder.java
Labels: priority.Medium, type.Enhancement

#79 Branch add tags
  src/main/java/seedu/address/logic/commands/AddTagsCommand.java
  src/main/java/seedu/address/logic/parser/AddTagsCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/AddTagsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTagsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindTagsAndCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Story

#65 Add profile panel in Ui
  README.md
  build.gradle
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonProfile.java
  src/main/resources/images/profile.jpg
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonProfile.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/IsSamePersonPredicateTest.java
Labels: enhancement, priority.High, type.Enhancement

#84 Edit gradle file to enable assertions
  build.gradle
Labels: priority.High

#87 Add select feature design details
  docs/DeveloperGuide.md
  docs/diagrams/SelectSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: documentation, priority.High

#94 Update images and select command
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/select1Result.png
Labels: documentation, priority.Medium

#96 Yunchao/dg update two
  docs/DeveloperGuide.md
Labels: documentation

#95 Update Person Card
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonProfile.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement

#98 Fix bug add command not adding client in order
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/person/LastContact.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/LastContactTest.java
Labels: bug
