Repository AY2324S2-CS2103T-F13-2/tp, pull requests merged in 2024-04, with the labels that each got.

#99 Bug fix last contact not filtering properly
  src/main/java/seedu/address/logic/commands/LastContactCommand.java
Labels: bug

#100 Yunchao/upcoming future date only
  src/main/java/seedu/address/model/person/LastContact.java
  src/main/java/seedu/address/model/person/Upcoming.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UpcomingTest.java
Labels: bug

#104 Update and clean up UserGuide
  docs/UserGuide.md
Labels: documentation, priority.High

#157 Fix bug where UI not updated after adding tags
  src/main/java/seedu/address/logic/commands/AddTagsCommand.java
Labels: bug

#156 Add details to UG to cover PE-D issues raised and fixed bugs mentioned in PE-D
  docs/UserGuide.md
  src/main/java/seedu/address/model/tag/Tag.java
Labels: bug, documentation

#164 Update documents
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: documentation

#163 Fix hard app crash bug when editing field thru json
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: bug

#166 Yunchao/almost final dg update
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: bug, documentation
